export const galleryImages = [
  {
    src: "/images/gallery/01.webp",
    alt: "",
    width: 719,
    height: 1280,
  },
  {
    src: "/images/gallery/02.webp",
    alt: "",
    width: 741,
    height: 1317,
  },
  {
    src: "/images/gallery/03.webp",
    alt: "",
    width: 960,
    height: 1280,
  },
  {
    src: "/images/gallery/04.webp",
    alt: "",
    width: 960,
    height: 1280,
  },
  {
    src: "/images/gallery/05.webp",
    alt: "",
    width: 719,
    height: 1280,
  },
  {
    src: "/images/gallery/06.webp",
    alt: "",
    width: 720,
    height: 1280,
  },
  {
    src: "/images/gallery/07.webp",
    alt: "",
    width: 1266,
    height: 2250,
  },
  {
    src: "/images/gallery/08.webp",
    alt: "",
    width: 1024,
    height: 1280,
  },
  {
    src: "/images/gallery/09.webp",
    alt: "",
    width: 1172,
    height: 659,
  },
  {
    src: "/images/gallery/10.webp",
    alt: "",
    width: 719,
    height: 1280,
  },
  {
    src: "/images/gallery/11.webp",
    alt: "",
    width: 960,
    height: 1280,
  },
  {
    src: "/images/gallery/12.webp",
    alt: "",
    width: 1280,
    height: 544,
  },
  {
    src: "/images/gallery/13.webp",
    alt: "",
    width: 276,
    height: 490,
  },
  {
    src: "/images/gallery/14.webp",
    alt: "",
    width: 1280,
    height: 720,
  },
  {
    src: "/images/gallery/15.webp",
    alt: "",
    width: 2816,
    height: 3754,
  },
  {
    src: "/images/gallery/16.webp",
    alt: "",
    width: 1280,
    height: 544,
  },
  {
    src: "/images/gallery/17.webp",
    alt: "",
    width: 1280,
    height: 1280,
  },
  {
    src: "/images/gallery/18.webp",
    alt: "",
    width: 741,
    height: 1280,
  },
  {
    src: "/images/gallery/19.webp",
    alt: "",
    width: 1849,
    height: 3287,
  },
  {
    src: "/images/gallery/20.webp",
    alt: "",
    width: 1280,
    height: 544,
  },
  {
    src: "/images/gallery/21.webp",
    alt: "",
    width: 1280,
    height: 719,
  },
  {
    src: "/images/gallery/22.webp",
    alt: "",
    width: 1023,
    height: 1280,
  },
  {
    src: "/images/gallery/23.webp",
    alt: "",
    width: 1280,
    height: 719,
  },
  {
    src: "/images/gallery/24.webp",
    alt: "",
    width: 960,
    height: 1280,
  },
];
